### ISSUE TITLE
April 15th meeting

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/notes#110]
@babel/babel feel free to add items to the agenda!

- [ ] Focus: Babel 8
- [ ] Discuss about an official RFC policy
    RFCs ideas from the team:
    - Move `targets` to the top-level options
    - Move `@babel/preset-env` into `@babel/core`
    - Allow plugin specific config to be overridden in `@babel/preset-env`
    - Versioning
- [ ] Make the polyfills plugins repo public to get feedback from the community (cc @ljharb if you have anything to say about this, you are welcome to join us!)
- [ ] Move `preset-modules` to `preset-env` and archive `preset-modules`

---

I don't have any preference regarding when we can schedule this, feel free to propose any time slot no later than 21:00-22:00 UTC.

**Comment by ljharb** [comment]
When is the meeting? I'd love to join but would need to calendar it.

**Comment by xtuc** [comment]
@ljharb I went ahead and added you to the calendar event

**Comment by nicolo-ribaudo** [comment]
Note that the calendar reflects the old meetings, so if needed we can change it.

If no one has problems with the current time slot, we can keep it.
