### ISSUE TITLE
May 7th Meeting

### ISSUE THREAD

**Issue by JLHwung** [babel/notes#114]
@babel/babel feel free to add items to the agenda!

- [ ] Feedback on https://github.com/babel/babel/pull/11508 (Justin)
- [ ] Feedback on https://github.com/babel/rfcs/pull/2 (Nicolò)
- [ ] Feedback on https://github.com/babel/rfcs/pull/4 (Jùnliàng)
- [ ] Building consensus on https://github.com/estree/estree/pull/204#issuecomment-624441739 (Jùnliàng)
- [ ] Investigate using TypeScript in our code
- [ ] Nicolò's summer
- [ ] Henry: showing REPL stuff with codesandbox ([example](https://codesandbox.io/s/babel-plugin-options-only-wci0w)) - what can we do with this?
- [ ] Henry: OC has some updates on the UI (just to mention it and maybe give a review) https://github.com/opencollective/opencollective-frontend/pull/4119

(@nicolo-ribaudo I just assume you would like talk about https://github.com/babel/rfcs/pull/2, feel free to revise it if you have different topics.)

**Comment by nicolo-ribaudo** [comment]
https://github.com/babel/notes/pull/115
