### ISSUE TITLE
Summer of Code ideas

### ISSUE THREAD

**Issue by hzoo** [babel/notes#14]
Discuss here!

This would usually mean some task that is really helpful to us but we might not have time to do. Summer of Code is a 3 month long full time effort so we can do a lot here.

Ideas: https://github.com/babel/babel/wiki/Google-Summer-of-Code-Proposals

> Create Babel parser/transform plugins for proposals in TC39
> REPL Examples
> Make ASTExplorer Standalone
> Rewrite Lebab as a Babel preset
> Babel Minify

This doesn't have to be the core of Babel, but everything around it (better website, REPL, docs, educational material, etc)

### Still need to add to wiki

- [ ] babel-init
- [ ] babel --settings
- [ ] test262 integration

**Comment by datwheat** [comment]
I'd love to participate in the GOSC with Babel but I won't be eligible by the summer. I'll be enrolled in college but I'll be a few months younger than 18 years old which is really unfortunate. If I could help out in any way, please let me know! 👍

**Comment by loganfsmyth** [comment]
@datwheat Contribitions from anyone are welcome. The best way to join the community would be to come hang out in our Slack.

**Comment by hzoo** [comment]
GSOC has started, will make a new issue
