### ISSUE TITLE
Join a foundation

### ISSUE THREAD

**Issue by xtuc** [babel/notes#50]
Following a discussion we had on Slack (https://babeljs.slack.com/archives/C0DFJT81H/p1513090060000158).

The possible options are the following:
- Join the JS foundation (at least 2x :-1: on our side)
- Create on our foundation (need probably to ask a lawyer?)
- Join another foundation (any ideas?)

Joining/becoming a foundation will allow us the following:
- Officially be part TC39 (note that some members are already)
- Donation are tax free (at least here in France)
- Consolidate our governance model

**Comment by ljharb** [comment]
I'd be interested to hear from the two thumbs downs about the JS Foundation - why not?

**Comment by xtuc** [comment]
I'm one of the two guys, I feel like that the JS foundation (which is backend by the Linux foundation) is just like a huge company where we will probably loose our decision power and/or some liberties.

It would be interesting to me to hear what the webpack guys experience is about that.

**Comment by hzoo** [comment]
@ljharb I don't want to join a JS Foundation just because it will allow us to attend TC39, we should be able to attend in another way or a reason that TC39's process should change? There are other reasons: have to change the license/add the CLA/give up certain things, and also no practical benefit on the things that we care about and have been working toward like getting contributors/maintainers/funding/etc. I haven't seen the foundation help with anything like that except act as more of a "backup plan" if everyone decides to leave. Not sure if we want to discuss this on github like this but those are some of my thoughts.

**Comment by ljharb** [comment]
@hzoo not solely for that reason, surely, but there's tons of reasons babel belongs in *a* foundation, and the JS Foundation is a good one.

You absolutely would not have to give up anything *whatsoever*; the JS Foundation in particular is big on letting projects decide things for themselves.

**Comment by ljharb** [comment]
In addition, you lose no "decision power" whatsoever; indeed the only place the foundation steps in is when "everyone leaves" or when everyone is at an intractable standstill.

None of the things you have both mentioned are downsides that actually exist here.

**Comment by thejameskyle** [comment]
Years ago we were approached by the JS Foundation (was jQuery at the time), and people shared some really horrible stories with us. I would be strongly against Babel ever joining the JS Foundation.

**Comment by azz** [comment]
Start an ES Foundation!

**Comment by ljharb** [comment]
I believe the jquery foundation had a different setup; I’m interested to hear those stories, but I’m not sure they’d still be relevant to the JS Foundation.

**Comment by xtuc** [comment]
@azz what is that ES Foundation you're referring to? Could you please send us a link?

**Comment by bebraw** [comment]
[Enough Foundations Already! by Simon Phipps](https://www.youtube.com/watch?v=ybAiTpqanDY) is a good watch (about 14 mins). There are a lot of good points to consider.

Instead of maintaining my own, I might look into joining an umbrella foundation. Then you get a question which to join, though.

**Comment by azz** [comment]
@xtuc Sorry, it was a poor attempt at humour, referencing JSLint → ESLint.

**Comment by littledan** [comment]
@bebraw That talk seems to specifically call out foundations to help participate in standards bodies. This is exactly what I'd like to encourage with Babel, to participate in TC39.

Currently, I'm working with others in TC39 to look into whether ECMA could continue to allow Babel to continue to participate as is, but it is uncertain how this will turn out. It's very possible that ECMA will request that Babel be something a a bit more formal. ECMA has allowed not-for-profit organizations to become ECMA members for free, a pretty generous policy given how much companies pay to participate, the only thing is to somehow join a not-for-profit organization or participate in one.

**Comment by xtuc** [comment]
We discussed that during multiple Babel meetings and we're not interested in that (at the moment).
