### ISSUE TITLE
Babel meeting - november 19th

### ISSUE THREAD

**Issue by xtuc** [babel/notes#73]
## Agenda

- [x] Debugging story (better errors) https://github.com/babel/babel/issues/6856
- [x] Pipeline Operator PR: babel/babel#8289 by @mAAdhaTTah 
- [x] Minor output optimizations (defineProperty calls folding): https://github.com/babel/babel/pull/6652#issuecomment-436322239 by @Andarist
- [x] Merged class features public interface https://github.com/babel/babel/pull/8130#discussion_r231754468 by @nicolo-ribaudo/Logan
- [x] Add a new flag to the decorators plugin for initializers? https://github.com/babel/babel/pull/9008#issuecomment-439065180 by @nicolo-ribaudo
- [x] Merge this potential bc or wait till babel 8? https://github.com/babel/babel/pull/8787 by @danez

**Comment by xtuc** [comment]
cc @babel/babel feel free to add items to the agenda!

**Comment by mAAdhaTTah** [comment]
Pipeline Operator PR: https://github.com/babel/babel/pull/8289

**Comment by Andarist** [comment]
Minor output optimizations (defineProperty calls folding): https://github.com/babel/babel/pull/6652#issuecomment-436322239

Would be great to establish if this is something that we want to do in babel in general (more optimized code - in some way, vs more readable code)
