### ISSUE TITLE
Babel meeting - december 17th

### ISSUE THREAD

**Issue by xtuc** [babel/notes#75]
## Agenda

- [x] An eslint plugin to help authors of Babel plugins: https://github.com/babel/eslint-plugin-babel-plugin. Do we want to publish it? (by @nicolo-ribaudo)
- [x] Do we want to keep v6 backport PRs open?
- [x] Class features: next steps. (@nicolo-ribaudo)
- [x] JSConf EU 2019 and TC39 (@xtuc)

@babel/babel  feel free to add items to the agenda!

**Comment by nicolo-ribaudo** [comment]
babel/babel#9050 (comment)
If we are going to disallow direct usage of @babel/plugin-class-features, it can only create confusion. We can rename it to @babel/helper-class-features so that noone tries to ue it directly.

**Comment by nicolo-ribaudo** [comment]
An eslint plugin to help authors of Babel plugins: https://github.com/babel/eslint-plugin-babel-plugin. Do we want to publish it?
