### ISSUE TITLE
Babel meeting - January 14th

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/notes#77]
## Agenda

- [x] Do we want Babel to be compatible with ESTree ASTs?
    We already have a parser plugin to generate ESTree-compliant ast, but `@babel/types` and `@babel/traverse` don't work with it.
    Ref: babel/babel#9253, babel/babel#9258
    (On slack: Out of scope, ESTree was only added to make babel-eslint work better)
- [x] `babel-eslint`: How do we handle missing Babel config files in v11?
    Ref: babel/babel-eslint#738 (by @kaicataldo)
- [x] `core-js@3`. It is really hard not to make breaking changes. Please read the PR description: https://github.com/babel/babel/pull/7646
- [x] Babel 7.3.0
- [x] Syntax support for placeholders (@nicolo-ribaudo and @tolmasky)
    Ref: https://github.com/babel/babel/issues/9112)
- [x] Henry: what's our next "core" feature?
  - https://github.com/babel/website/blob/master/docs/roadmap.md
  - Infra: test262
  - Docs: polyfills
  - Website: REPL + codesandbox

@babel/babel  feel free to add items to the agenda!

**Comment by kaicataldo** [comment]
Hi! I'd love to discuss https://github.com/babel/babel-eslint/issues/738 so that we can figure out how we want to do the next babel-eslint release.

**Comment by chicoxyzzy** [comment]
`core-js@3` link is broken. Should it be https://github.com/babel/babel/pull/7646?

**Comment by xtuc** [comment]
Yes @chicoxyzzy, thanks
